In [198]:
import numpy as np
with open('input/2022_12_12_input') as file:
    f = file.read()
        
#clean =' '.join(f.strip()).replace('\n', ';').replace(' ;', ';').replace('; ', ';')
#matrix = np.matrix(clean)

f_test = '''Sabqponm
abcryxxl
accszExk
acctuvwj
abdefghi
'''

string = f
matrix = np.zeros((41, 171))

#string = f_test
#matrix = np.zeros((5, 8))


for row in range(0, len(string.splitlines())):
    for col in range (0, len(string.splitlines()[0])):
        matrix[row, col] = ord(string.splitlines()[row][col])
        
matrix2 = []
for a in string.splitlines():
    matrix2.append(list(a))

In [199]:
start = np.where(matrix == ord('S'))
end = np.where(matrix == ord('E'))
print(start, end)

matrix[start] = 97
matrix[end] = 122

print(start, end)

(array([20]), array([0])) (array([20]), array([146]))
(array([20]), array([0])) (array([20]), array([146]))


In [200]:
matrix

array([[97., 98., 99., ..., 97., 97., 97.],
       [97., 98., 99., ..., 97., 97., 97.],
       [97., 98., 99., ..., 97., 97., 97.],
       ...,
       [97., 98., 97., ..., 97., 97., 97.],
       [97., 98., 97., ..., 97., 97., 97.],
       [97., 98., 97., ..., 97., 97., 97.]])

In [201]:
current_pos_x = end[0][0]
current_pos_y = end[1][0]
counter = 0
while (current_pos_x != start[0][0] or current_pos_y != start[1][0]) and counter < 40:
    if current_pos_x-1 >= 0:
        up_diff = matrix[current_pos_x, current_pos_y] - matrix[current_pos_x-1, current_pos_y]
    else:
        up_diff = 2
    if current_pos_x+1 <= len(matrix)-1:
        down_diff = matrix[current_pos_x, current_pos_y] - matrix[current_pos_x+1, current_pos_y]
    else:
        down_diff = 2
    if current_pos_y-1 >= 0:
        left_diff = matrix[current_pos_x, current_pos_y] - matrix[current_pos_x, current_pos_y-1]
    else:
        left_diff = 2
    if current_pos_y+1 <= len(matrix[0])-1:
        right_diff = matrix[current_pos_x, current_pos_y] - matrix[current_pos_x, current_pos_y+1]
    else:
        right_diff = 2
 
    
    matrix[current_pos_x][current_pos_y] = 0

    if left_diff <= 1:
        print('left')
        matrix2[current_pos_x][current_pos_y] = '<'
        current_pos_y -= 1
    elif up_diff == 1 or (up_diff == 0 and down_diff!=1):
        print('up')
        matrix2[current_pos_x][current_pos_y]= '^'        
        current_pos_x -= 1
    elif down_diff == 1 or (down_diff == 0 and up_diff!=1):
        print('down')
        matrix2[current_pos_x][current_pos_y] = 'v'        
        current_pos_x += 1
    elif right_diff <=1:
        print('right')
        matrix2[current_pos_x][current_pos_y] = '>'
        current_pos_y += 1
    else:
        print('wrong path')
        break
    counter += 1


right
right
down
left
left
left
left
left
up
right
right
up
right
up
up
up
right
up
right
down
down
left
down
down
right
up
right
up
up
up
wrong path


In [196]:
matrix2

[['S', 'a', 'b', '>', '>', '>', '>', 'v'],
 ['^', 'b', 'c', '^', '>', '>', 'v', 'v'],
 ['^', 'c', 'c', '^', '^', '<', 'v', 'v'],
 ['^', 'v', '<', '^', '<', '<', '<', 'v'],
 ['^', '<', '^', '<', '<', '<', '<', '<']]

In [197]:
matrix

array([[97., 97., 98.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 98., 99.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 99., 99.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])